server:
  port: 8080


spring:
  application:
    version: ${random.long}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.4.17:4444/ming
    username: postgres
    password: postgres
  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect    #与jts_geometry相关
          temp:
            use_jdbc_metadata_defaults: false
      show-sql: true



swagger:
  enabled: true
  title: 开发文档
  version: ${spring.application.version}
  description: 开发文档
  exclude-path: /error,/actuator/**
  contact:
    name: CoderLG
    email: im.lg@qq.com
