server:
  port: 8080

spring:
  datasource:
    master:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.4.18:5432/lg
      username: postgres
      password: postgres
    slave:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.4.18:5432/gang
      username: postgres
      password: postgres
    third:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.4.18:5432/gg
      username: postgres
      password: postgres

  jpa:
      hibernate:
        ddl-auto: update