spring:
  datasource:
    url: jdbc:mysql://localhost:3306/home
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: lg.tkentity
#  mapper-locations: classpath:mybatis/mappers/**/*.xml

pagehelper:
  helper-dialect: mysql




